language: node_js
node_js:
  - "10"
before_script:
  - npx version-from-git --travis --no-git-tag-version
  - npm run bootstrap
  - node scripts/syncVersion
  - npm run build
before_deploy:
  - cp -r packages/component/lib .
deploy:
  # Since we are using Lerna without hoist (conflict between babel@6 and babel@7), thus, we cannot use npm provider to deploy
  # - provider: npm
  #   api_key:
  #     secure: ""
  #   email: "compulim@hotmail.com"
  #   on:
  #     branch: master
  #   skip_cleanup: true
  #   tag: master
  # - provider: npm
  #   api_key:
  #     secure: ""
  #   email: "compulim@hotmail.com"
  #   on:
  #     tags: true
  #   skip_cleanup: true
  - provider: pages
    skip-cleanup: true
    github-token:
      secure: ""
    on:
      branch: master
    local-dir: packages/playground/build
  - provider: releases
    api_key:
      secure: ""
    on:
      tags: true
    skip_cleanup: true
